dist: xenial
language: java

cache:
  directories:
    - $HOME/.m2

jdk:
  - openjdk8
  - openjdk11
  - openjdk14

before_install: ./travis/sign.sh

script:
  - ./mvnw clean install -B
  # fail build if there are any local changes to sources
  - ./travis/no-git-changes.sh

jobs:
  include:
    - stage: snapshot
      name: "Deploy Snapshot to OSSRH"
      if: branch = master AND type != pull_request AND commit_message !~ /^(prepare release ([0-9\.]+))$/
      jdk: openjdk8
      install: true
      script:
        - ./mvnw -B -nsu -s ./travis/settings.xml -P release -pl -:feign-benchmark -DskipTests=true deploy
    - stage: release
      name: "Release to OSSRH and Central"
      if: tag =~ /^[0-9\.]+$/
      # there is one module (java-11) that needs to be build and released with JDK 11
      jdk: openjdk8
      install: true
      script:
        - ./mvnw -B -nsu -s ./travis/settings.xml -P release -pl -:feign-benchmark -DskipTests=true deploy
    - stage: release-jdk11
      name: "Release JDK 11 Modules to OSSRH and Central"
      if: tag =~ /^[0-9\.]+$/
      jdk: openjdk11
      install: true
      script:
        # first install the pre-requisite projects, then deploy just the java 11 module
        - ./mvnw -B -nsu -s ./travis/settings.xml -P java11 -pl :feign-java11 -am -DskipTests=true install
        - ./mvnw -B -nsu -s ./travis/settings.xml -P release,java11 -pl :feign-java11 -DskipTests=true deploy
